-- Add new columns to bookings table
ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS start_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS end_time TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS total_hours DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS total_amount DECIMAL(10,2); 