-- Add missing columns to bookings table
ALTER TABLE bookings
ADD COLUMN IF NOT EXISTS start_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS end_date TIMESTAMP WITH TIME ZONE,
ADD COLUMN IF NOT EXISTS total_hours DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS total_price DECIMAL(10,2); 