-- Add new columns to bookings table without dropping existing data
ALTER TABLE "bookings"
ADD COLUMN IF NOT EXISTS "customer_name" TEXT,
ADD COLUMN IF NOT EXISTS "phone_number" TEXT,
ADD COLUMN IF NOT EXISTS "alternate_phone" TEXT,
ADD COLUMN IF NOT EXISTS "dl_number" TEXT,
ADD COLUMN IF NOT EXISTS "dl_expiry_date" TIMESTAMPTZ,
ADD COLUMN IF NOT EXISTS "permanent_address" TEXT,
ADD COLUMN IF NOT EXISTS "vehicle_model" TEXT,
ADD COLUMN IF NOT EXISTS "registration_number" TEXT,
ADD COLUMN IF NOT EXISTS "purpose_of_rent" TEXT,
ADD COLUMN IF NOT EXISTS "payment_method" TEXT,
ADD COLUMN IF NOT EXISTS "paid_amount" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "due_amount" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "payment_status" TEXT,
ADD COLUMN IF NOT EXISTS "payment_reference" TEXT,
ADD COLUMN IF NOT EXISTS "security_deposit_amount" DECIMAL(10,2),
ADD COLUMN IF NOT EXISTS "dl_scan" TEXT,
ADD COLUMN IF NOT EXISTS "aadhar_scan" TEXT,
ADD COLUMN IF NOT EXISTS "selfie" TEXT,
ADD COLUMN IF NOT EXISTS "agreement_scan" TEXT,
ADD COLUMN IF NOT EXISTS "original_dl_verified" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "voter_id_verified" BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS "terms_accepted" BOOLEAN DEFAULT false; 